name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: [ self-hosted, 1ES.Pool=1es-github-public-iter3 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "Hello, World!"

      - name: Echo IP Address
        run: echo "IP Address $(ip a)"